apiVersion: v1
kind: Service
metadata:
  name: operationcode-frontend-service
spec:
  selector:
    app: operationcode-frontend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 4000
  type: ClusterIP
