apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operationcode-staging

bases:
- ../../base

resources:
- redis-service.yaml
- database-service.yaml

patchesStrategicMerge:
  - deployment.yaml