apiVersion: v1
kind: Service
metadata:
  name: back-end-service
spec:
  selector:
    app: back-end
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  type: NodePort
