apiVersion: v1
kind: Service
metadata:
  name: operationcode-backend-service
spec:
  selector:
    app: operationcode-backend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
